--liquibase formatted sql

--changeset Jeffrey Williams:InitialSchemaCreation runOnChange:false splitStatements:true Comment:Adding Initial Schema Description:A Description
CREATE TABLE AIRLINES
   (
		AIRLINE CHAR(2) NOT NULL CONSTRAINT AIRLINES_PK PRIMARY KEY,
		AIRLINE_FULL VARCHAR(24),
		BASIC_RATE DOUBLE PRECISION,
		DISTANCE_DISCOUNT DOUBLE PRECISION,
		BUSINESS_LEVEL_FACTOR DOUBLE PRECISION,
		FIRSTCLASS_LEVEL_FACTOR DOUBLE PRECISION,
		ECONOMY_SEATS INTEGER,
		BUSINESS_SEATS INTEGER,
		FIRSTCLASS_SEATS INTEGER
   );

CREATE TABLE COUNTRIES
   (
		COUNTRY VARCHAR(26) NOT NULL CONSTRAINT COUNTRIES_UNQ_NM Unique,
		COUNTRY_ISO_CODE CHAR(2) NOT NULL CONSTRAINT COUNTRIES_PK PRIMARY KEY,
		REGION VARCHAR(26),
		CONSTRAINT COUNTRIES_UC CHECK (country_ISO_code = upper(country_ISO_code) )
   );
 
CREATE TABLE CITIES
   (
		CITY_ID INTEGER NOT NULL CONSTRAINT CITIES_PK PRIMARY KEY,
		CITY_NAME VARCHAR(24) NOT NULL,
		COUNTRY VARCHAR(26) NOT NULL,
		AIRPORT VARCHAR(3),
		LANGUAGE  VARCHAR(16),
		COUNTRY_ISO_CODE CHAR(2) CONSTRAINT COUNTRIES_FK
		REFERENCES COUNTRIES (COUNTRY_ISO_CODE)
   );

CREATE TABLE MAPS
   (
		MAP_ID INTEGER NOT NULL CONSTRAINT MAPS_PK PRIMARY KEY,
		MAP_NAME VARCHAR(24) NOT NULL,
		REGION VARCHAR(26),
		AREA DECIMAL(8,4) NOT NULL,
		PHOTO_FORMAT VARCHAR(26) NOT NULL,
		PICTURE BYTEA,
		UNIQUE (MAP_ID, MAP_NAME)
   );

CREATE TABLE FLIGHTS
   (
		FLIGHT_ID CHAR(6) NOT NULL ,
		SEGMENT_NUMBER INTEGER NOT NULL ,
		ORIG_AIRPORT CHAR(3),
		DEPART_TIME TIME,
		DEST_AIRPORT CHAR(3),
		ARRIVE_TIME TIME,
		MEAL CHAR(1),
		FLYING_TIME DOUBLE PRECISION,
		MILES INTEGER,
		AIRCRAFT VARCHAR(6),
		CONSTRAINT FLIGHTS_PK PRIMARY KEY (
							FLIGHT_ID,
							SEGMENT_NUMBER),
		CONSTRAINT MEAL_CONSTRAINT  CHECK (meal IN ('B', 'L', 'D', 'S'))
   );

CREATE INDEX DESTINDEX ON FLIGHTS (DEST_AIRPORT);
  
CREATE INDEX ORIGINDEX ON FLIGHTS (ORIG_AIRPORT);
 
CREATE TABLE FLIGHTAVAILABILITY
   (
		FLIGHT_ID CHAR(6) NOT NULL ,
		SEGMENT_NUMBER INTEGER NOT NULL ,
		FLIGHT_DATE DATE NOT NULL ,
		ECONOMY_SEATS_TAKEN INTEGER DEFAULT 0,
		BUSINESS_SEATS_TAKEN INTEGER DEFAULT 0,
		FIRSTCLASS_SEATS_TAKEN INTEGER DEFAULT 0,
		CONSTRAINT FLIGHTAVAIL_PK PRIMARY KEY (
								  FLIGHT_ID,
								  SEGMENT_NUMBER,
								  FLIGHT_DATE),
		CONSTRAINT FLIGHTS_FK2 Foreign Key (
			FLIGHT_ID,
			SEGMENT_NUMBER)
		 REFERENCES FLIGHTS (
			FLIGHT_ID,
			SEGMENT_NUMBER)
   );

CREATE TABLE FLIGHTS_HISTORY
   (
		FLIGHT_ID CHAR(6),
		SEGMENT_NUMBER INTEGER,
		ORIG_AIRPORT CHAR(3),
		DEPART_TIME TIME,
		DEST_AIRPORT CHAR(3),
		ARRIVE_TIME TIME,
		MEAL CHAR(1),
		FLYING_TIME DOUBLE PRECISION,
		MILES INTEGER,
		AIRCRAFT VARCHAR(6), 
		STATUS VARCHAR (20)
   );